# Generated by Django 3.2.dev20200804083438 on 2020-12-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=150)),
                ('starting_bid', models.IntegerField()),
                ('image_link', models.CharField(max_length=400)),
            ],
        ),
    ]
