# Generated by Django 3.2.dev20200804083438 on 2020-12-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201229_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='active',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Active', 'Active'), ('Close', 'Close')], max_length=200, null=True),
        ),
    ]
