# Generated by Django 3.2.dev20200804083438 on 2020-12-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_product_won_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_won',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_won', to='auctions.listing', unique=True),
        ),
    ]
